import type { Metadata } from "next";
import "./globals.css";
import { PropsWithChildren } from "react";

import { Header, Sidebar } from "@/components";

export const metadata: Metadata = {
  title: "Soar Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap');
        </style>
      </head>
      <body className="inter-regular min-h-screen text-black">
        <div className="flex flex-col sm:grid sm:grid-cols-[250px_1fr] sm:grid-rows-[100px_1fr] min-h-screen">
          <Header />
          <Sidebar />
          <main className="grow col-span-2 sm:col-span-1 py-container sm:py-big-container px-6 sm:px-10 bg-secondary">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
