import type { Metadata } from "next";
import "./globals.css";
import { PropsWithChildren } from "react";

import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Soar Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap');
        </style>
      </head>
      <body className="inter-regular min-h-screen text-black">
        <div className="grid grid-cols-[250px_1fr] grid-rows-[100px_1fr] min-h-screen">
          <Header />
          <Sidebar />
          <main className="py-8 px-10 bg-secondary">{children}</main>
        </div>
      </body>
    </html>
  );
}
