import type { Metadata } from "next";
import "./globals.css";
import { PropsWithChildren } from "react";

import { Header, Sidebar } from "@/components";

export const metadata: Metadata = {
  title: "Soar Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap');
          @import
          url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap');
        </style>
      </head>
      <body className="inter font-normal min-h-screen text-black">
        <div className="flex flex-col lg:grid lg:grid-cols-[250px_1fr] lg:grid-rows-[100px_1fr] min-h-screen">
          <Header />
          <Sidebar />
          <main className="grow col-span-2 lg:col-span-1 py-container lg:py-big-container px-6 lg:px-10 bg-secondary">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
